### ISSUE TITLE
Run Project with #define LV_USE_DRAW_SW 0 does not work

### ISSUE THREAD

**Issue by FloHomi** [lvgl/lv_port_renesas_ek-ra8d1_gcc#9] opened 2024-05-15 13:14 UTC
Hi, 
I need to run the Project in BareMetal and need to turn off "LV_USE_DRAW_SW" in lv_config.c
In the old Git version it worked(but showed no performance differnce. Now, with the latest git version it shows a black screen. Dave2D is on. 

```
...
#define LV_USE_DRAW_SW 0
...
#define LV_USE_DRAW_DAVE2D 1
...
```
Any Idea why this is happening?

**Comment by kisvegabor** [comment] 2024-05-20 17:25
I've tested it with EK-RA8D1 and it worked with a simple label but not with `lv_demo_widgets()`. 

I suspect that the problem is that DAVE2D can't handle all the draw tasks, and if there is no SW render as a fallback, LVGL hangs. 

Before jumping into fixing it, please confirm that it works on your end too with a single label.

**Comment by FloHomi** [comment] 2024-05-22 08:03
I can confirm!
Label ist fine. Adding a Button, breaks it.

**Comment by kisvegabor** [comment] 2024-05-27 18:49
Thanks, it's should be fixed by https://github.com/lvgl/lvgl/pull/6290

**Comment by FloHomi** [comment] 2024-06-05 12:46
Thank you very much 👍

**Closed as completed** 2024-06-05 12:46 UTC
